package org.java_juc.begginer_level.thread_pool_12.thread_pool_theory.pool_cache;

import java.time.LocalDateTime;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 * Supermarket : 10 caisses max, traiter 10 consommateurs, 20 consommateurs, etc.
 */
public class ThreadPoolCacheThread {
    public static void main(String[] args) throws InterruptedException {

        // create thread pool
        ExecutorService threadPool = Executors.newCachedThreadPool();

        int startTime = 0;
        int executeTime;
        int endTime;
        try {
            startTime = LocalDateTime.now().getNano();

            for (int i = 1; i <= 20; i++) {

                // exécuter
                threadPool.execute(() -> {
                    System.out.println(Thread.currentThread().getName() + " est train de encaisser...");
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // put the thread dans le pool
            threadPool.shutdown(); // be careful shutdownNow()!
            endTime = LocalDateTime.now().getNano();
        }

        TimeUnit.SECONDS.sleep(2);
        executeTime = endTime - startTime;

        System.out.println(executeTime);
    }
}
/* possible result:
pool-1-thread-1 est train de encaisser...
pool-1-thread-2 est train de encaisser...
pool-1-thread-4 est train de encaisser...
pool-1-thread-5 est train de encaisser...
pool-1-thread-3 est train de encaisser...
pool-1-thread-6 est train de encaisser...
pool-1-thread-8 est train de encaisser...
pool-1-thread-10 est train de encaisser...
pool-1-thread-9 est train de encaisser...
pool-1-thread-7 est train de encaisser...
19000000 avec 10 personnes
 */
/* possible result:
pool-1-thread-1 est train de encaisser...
pool-1-thread-4 est train de encaisser...
pool-1-thread-3 est train de encaisser...
pool-1-thread-2 est train de encaisser...
pool-1-thread-4 est train de encaisser...
pool-1-thread-6 est train de encaisser...
pool-1-thread-1 est train de encaisser...
pool-1-thread-5 est train de encaisser...
pool-1-thread-7 est train de encaisser...
pool-1-thread-8 est train de encaisser...
pool-1-thread-9 est train de encaisser...
pool-1-thread-10 est train de encaisser...
pool-1-thread-2 est train de encaisser...
pool-1-thread-9 est train de encaisser...
pool-1-thread-5 est train de encaisser...
pool-1-thread-1 est train de encaisser...
pool-1-thread-10 est train de encaisser...
pool-1-thread-7 est train de encaisser...
pool-1-thread-8 est train de encaisser...
pool-1-thread-6 est train de encaisser...
22000000
 */


// 15000000 nThread, 16000000 oneThread,22000000 cacheThread
